apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: {{ .Release.Name }}-scheduler-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Release.Name }}-scheduler-role
  subjects:
  - kind: ServiceAccount
    name: {{ include "scheduler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
kind: List
metadata: {}