{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler.serviceAccountName" . }}
  labels:
{{ include "scheduler.labels" . | nindent 4 }}
{{- end -}}
