# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateSkeleton <- function(mat, alpha = 0.05, maxCondSize = 4L, NAdelete = 1L, verbose = FALSE) {
    .Call(`_gpucausalrcpp_estimateSkeleton`, mat, alpha, maxCondSize, NAdelete, verbose)
}

rpmccOwn <- function(mat) {
    .Call(`_gpucausalrcpp_rpmccOwn`, mat)
}

rpmccOwnShared <- function(mat) {
    .Call(`_gpucausalrcpp_rpmccOwnShared`, mat)
}

