if: branch = master

sudo: required
language: python
services:
  - docker
install:
  - bash scripts/bootstrap.sh
script:
  - docker-compose run backend flake8
  - docker-compose run backend flask db upgrade
  - docker-compose run backend pytest
git:
  submodules: false