sudo: required
language: python
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_5f5c2a0edcd2_key -iv $encrypted_5f5c2a0edcd2_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
- cp confdefault/* conf/
- docker-compose build
script:
- docker-compose run backend flake8
- docker-compose run backend pytest
after_success:
- bash .travis/deploy.sh
