if: branch = master

sudo: required
language: python
services:
  - docker
install:
  - cp confdefault/* conf/
  - cd src/executionenvironments/r
  - docker build -t mpci_execution_r .
  - cd ../../..
  - docker-compose build
script:
  - docker-compose run backend flake8
  - docker-compose run backend flask db upgrade
  - docker-compose run backend pytest
git:
  submodules: false