version: '3'
services:
  backend:
    volumes:
     - ./:/app
    build: .
    ports:
     - 5000:5000
    depends_on:
      - database
    env_file:
      - conf/backend.env
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
  db-ui:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    depends_on:
      - database
