version: '3'
services:
  backend:
    container_name: backend
    volumes:
     - ./:/app
    build: .
    depends_on:
      - database
    env_file:
      - conf/backend.env
    environment:
      - API_HOST=ui:5000
    restart: on-failure
    command: "uwsgi --ini /app/uwsgi.ini"
  database:
    container_name: db
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    links:
      - backend
    depends_on:
      - backend
    ports:
    - 5000:5000
    restart: on-failure
  db-ui:
    container_name: db-ui
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    depends_on:
      - database
    restart: on-failure
