version: '3'
services:
  backend:
    volumes:
     - ./:/app
    build: .
    ports:
     - 5000:5000
    depends_on:
      - database
    env_file:
      - conf/backend.env
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'