version: '3.7'
services:
  backend:
    volumes:
     - ./src:/app/src
     - /var/run/docker.sock:/var/run/docker.sock
    build: .
    ports:
     - 5000:5000
    depends_on:
      - database
      - scheduler
    env_file:
      - conf/backend.env
    environment:
      - API_HOST=backend:5000
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
  scheduler:
    volumes:
     - ./src:/app/src
     - /var/run/docker.sock:/var/run/docker.sock
    build: 
      context: .
      dockerfile: Dockerfile.scheduler
    depends_on:
      - database
    env_file:
      - conf/backend.env
    environment:
      - API_HOST=backend:5000
  db-ui:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
    depends_on:
      - database
    restart: on-failure
