version: '3'
services:
  backend:
    container_name: backend
    volumes:
     - ./:/app
     - /var/run/docker.sock:/var/run/docker.sock
    build: .
    depends_on:
      - database
    env_file:
      - conf/backend.env
    environment:
      - API_HOST=ui:5000
    restart: on-failure
  database:
    container_name: db
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    links:
      - backend
    depends_on:
      - backend
    ports:
    - 5000:5000
    restart: on-failure