version: '3'
services:
  backend:
    container_name: backend
    volumes:
     - ./:/app
    build: .
    depends_on:
      - database
    env_file:
      - conf/backend.env
    restart: on-failure
    command: "uwsgi --ini /app/uwsgi.ini"
  ui:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - backend
    depends_on:
      - backend
    ports:
    - 5000:5000
    restart: on-failure