FROM node

RUN apt-get update
RUN apt-get install -yq nginx

COPY ./static/swagger /var/www/mpci/swagger
COPY ./static/ui/yarn.lock /var/www/mpci/ui/yarn.lock
COPY ./static/ui/package.json /var/www/mpci/ui/package.json
COPY ./nginx.conf /etc/nginx/conf.d/nginx.conf

WORKDIR /var/www/mpci/ui

RUN npm install -g yarn
RUN yarn install

COPY ./static/ui/ /var/www/mpci/ui

RUN yarn run build

CMD ["nginx", "-g", "daemon off;"]