FROM danthe1/mpci_ui:latest

COPY ./static/swagger /var/www/mpci/swagger
COPY ./static/ui/package.json /var/www/mpci/ui/package.json
COPY ./static/ui/yarn.lock /var/www/mpci/ui/yarn.lock

WORKDIR /var/www/mpci/ui
RUN yarn install

COPY ./static/ui/ /var/www/mpci/ui
RUN yarn run build

COPY ./nginx.conf /etc/nginx/conf.d/nginx.conf
CMD ["nginx", "-g", "daemon off;"]
