FROM python:3.7

COPY requirements.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt
COPY conf confdefault src static/swagger scripts test nginx.conf requirements.txt job_scheduler.py setup.cfg ./
CMD ["python", "job_scheduler.py"]
