apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: milanpro/mpci_frontend
    context: .
    sync:
      infer: []
    docker:
      dockerfile: docker/frontend.Dockerfile
  - image: milanpro/mpci_backend
    context: .
    docker:
      dockerfile: docker/backend.Dockerfile
  - image: milanpro/mpci_scheduler
    context: .
    docker:
      dockerfile: docker/scheduler.Dockerfile
  # - image: milanpro/mpci_executor
  #   context: ./src/executionenvironments/r/
  #   docker:
  #     dockerfile: ./r-executor.Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: mpcicluster
      chartPath: helm/mpci
      skipBuildDependencies: true
profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: docker/frontend-dev.Dockerfile
      - op: add
        path: /build/artifacts/0/sync/infer
        value: ['./static/ui/src/**/*.{js,jsx,ts,tsx}']
    activation:
      - command: dev
      - command: debug