apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: milanpro/mpci_frontend
    context: .
    sync:
      infer: []
    docker:
      dockerfile: docker/frontend.Dockerfile
  - image: milanpro/mpci_backend
    context: .
    docker:
      dockerfile: docker/backend.Dockerfile
  - image: milanpro/mpci_scheduler
    context: .
    docker:
      dockerfile: docker/scheduler.Dockerfile
  - image: milanpro/mpci_executor
    context: .
    docker:
      dockerfile: docker/r-executor.Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: mpci-cluster
      chartPath: helm/mpci
profiles:
  - name: dev
    # build:
    #   artifacts:
    #     - image: milanpro/mpci_frontend
    #       context: .
    #       sync:
    #         infer: ['./static/ui/src/**/*.{js,jsx,ts,tsx}']
    #       docker:
    #         dockerfile: docker/frontend-dev.Dockerfile
    #     - image: milanpro/mpci_backend
    #       context: .
    #       docker:
    #         dockerfile: docker/backend.Dockerfile
    #     - image: milanpro/mpci_scheduler
    #       context: .
    #       docker:
    #         dockerfile: docker/scheduler.Dockerfile
    #     - image: milanpro/mpci_executor
    #       context: ./src/executionenvironments/r/
    #       docker:
    #         dockerfile: ../../../docker/r-executor.Dockerfile
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: docker/frontend-dev.Dockerfile
      - op: add
        path: /build/artifacts/0/sync/infer
        value: ['./static/ui/src/**/*.{js,jsx,ts,tsx}']
    activation:
      - command: dev
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      # skipBuildDependencies: false # Skip helm dep build
      # values:
      #   image: gcr.io/k8s-skaffold/skaffold-helm
      #   "skaffold-helm-subchart.image": gcr.io/k8s-skaffold/skaffold-helm
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.  
      #setValues:
        #some.key: someValue