grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: true
    path: /
    hosts:
      - vm-mpws2019.eaalab.hpi.uni-potsdam.de
    annotations:
      kubernetes.io/ingress.class: nginx
  persistence:
    enabled: true
    storageClassName: nfs-client
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-client-provisioner
