version: 2.1
orbs: 
  codecov: codecov/codecov@1.0.2
jobs:
  build-backend:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker build -t milanpro/mpci_backend:$CIRCLE_SHA1 -f docker/backend.Dockerfile .
  build-push-backend:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: echo "$DOCKERREG_TOKEN" | docker login --username milanpro --password-stdin
      - run: docker build -t milanpro/mpci_backend -f docker/backend.Dockerfile .
      - run: docker push milanpro/mpci_backend


  test:
    docker:
      - image: circleci/python:3.7.5
        environment:
          FLASK_APP: migration.py
      - image: postgres:12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: flask db upgrade 
      - run: flake8 test/ src/ seed.py server.py setup_algorithms.py job_scheduler.py
      - run: pytest --cov-report xml --cov=src test/
      - when:
          condition: on_success
          steps:
            - codecov/upload:
                file: coverage.xml
                conf: .codecov.yml



workflows:
  build-and-test:
    jobs:
      - build-backend:
          filters:
            branches:
              ignore:
                - master
      - build-push-backend:
          filters:
            branches:
              only:
                - master
      - test