version: 2.1
orbs: 
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    environment:
      DOCKER_COMPOSE_VERSION: 1.23.2
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: upgrade pip
          command: pip install --upgrade pip
      - run: 
          name: Get Dependencies
          command: git submodule update --init --recursive src/executionenvironments/r/pcalg
      - run: sudo snap install microk8s --classic
      - run: sudo microk8s.status --wait-ready
      - run: sudo microk8s.enable helm storage dns
      - run: sudo microk8s.helm init --wait
      - run: sudo microk8s.kubectl dependency update /home/circleci/project/helm/mpci/
      - run: sudo microk8s.helm install --name mpcicluster /home/circleci/project/helm/mpci/
      - run: sudo microk8s.kubectl exec -it $(kubectl get pods | grep -m1 backend |awk '{ print $1 }') flake8 test/ src/ seed.py server.py setup_algorithms.py job_scheduler.py
      - run: sudo microk8s.kubectl exec -it $(kubectl get pods | grep -m1 backend |awk '{ print $1 }') pytest --cov-report xml --cov=src test/



workflows:
  build-and-test:
    jobs:
      - build-and-test