version: 2.1
orbs: 
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    docker:
      - image: buildpack-deps:stable
    steps:
      - checkout
      - run: 
          name: Get Dependencies
          command: git submodule update --init --recursive src/executionenvironments/r/pcalg
      - run: 
          name: Build Stuff
          command: bash scripts/cibuild.sh
      - when:
          condition: on_success
          steps:
            - codecov/upload:
                file: coverage.xml
                conf: .codecov.yml


workflows:
  build-and-test:
    jobs:
      - build-and-test