version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: git submodule update --init --recursive src/executionenvironments/r/pcalg
      - run: bash scripts/cibuild.sh
      - run:
          when: on_success
          command: |
              export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
              codecov -b $BRANCH


