version: 2.1
orbs: 
  codecov: codecov/codecov@1.0.2
jobs:
  build-backend:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: echo "$DOCKERREG_TOKEN" | docker login --username milanpro --password-stdin
      - run: docker build -t milanpro/mpci_backend:$CIRCLE_BRANCH -f docker/backend.Dockerfile .
      - run: docker push milanpro/mpci_backend:$CIRCLE_BRANCH


  test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: sudo snap install microk8s --classic
      - run: sudo microk8s.status --wait-ready
      - run: sudo microk8s.enable helm storage dns
      - run: sudo microk8s.helm init --wait
      - run: sudo microk8s.helm dependency update helm/mpci/
      - run: sudo microk8s.helm install --name mpcicluster helm/mpci/ --set backend.image.tag=$CIRCLE_BRANCH
      - run: sleep 90
      - run: sudo microk8s.kubectl exec -it $(sudo microk8s.kubectl get pods | grep -m1 backend |awk '{ print $1 }') flake8 test/ src/ seed.py server.py setup_algorithms.py job_scheduler.py
      - run: sudo microk8s.kubectl exec -it $(sudo microk8s.kubectl get pods | grep -m1 backend |awk '{ print $1 }') pytest --cov-report xml --cov=src test/



workflows:
  build-and-test:
    jobs:
      - build-backend
      - test