version: 2
jobs:
  build:
    environment:  
      DOCKER_COMPOSE_VERSION: 1.23.2
    docker:
      - image: python
    steps:
      - run: apt install docker
      - checkout
      - run: git submodule update --init --recursive src/executionenvironments/r/pcalg
      - run: curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - run: chmod +x docker-compose
      - run: mv docker-compose /usr/local/bin
      - run: bash scripts/cibuild.sh
      - run:
          when: on_success
          command: |
              export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
              codecov -b $BRANCH


