version: 2
jobs:
  build-and-test:
    environment:
      DOCKER_COMPOSE_VERSION: 1.23.2
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: upgrade pip
          command: pip install --upgrade pip
      - run: 
          name: Get Dependencies
          command: git submodule update --init --recursive src/executionenvironments/r/pcalg
      - run: sudo rm /usr/local/bin/docker-compose
      - run: curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - run: chmod +x docker-compose 
      - run: sudo mv docker-compose /usr/local/bin
      - run: 
          name: Build Stuff
          command: bash scripts/cibuild.sh
      #- run: 
      #    name: Run Tests
      #    command: bash scripts/test.sh
      - run:
          name: On Success
          when: on_success
          command: |
              export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
              codecov -b $BRANCH
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test