version: 2.1
orbs: 
  codecov: codecov/codecov@1.0.2
jobs:
  build-backend:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: echo "$DOCKERREG_TOKEN" | docker login --username milanpro --password-stdin
      - run: docker build -t milanpro/mpci_backend:$CIRCLE_SHA1 -f docker/backend.Dockerfile .
      - run: docker push milanpro/mpci_backend:$CIRCLE_SHA1


  test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    environment:
      FLASK_APP: migration.py
    steps:
      - checkout
      - run: sudo apt-get install postgresql
      - run: pip install -r requirements.txt
      - run: flask db upgrade 
      - run: flake8 test/ src/ seed.py server.py setup_algorithms.py job_scheduler.py
      - run: pytest --cov-report xml --cov=src test/



workflows:
  build-and-test:
    jobs:
      - build-backend
      - test:
          requires:
            - build-backend