{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pgweb.serviceAccountName" . }}
  labels:
{{ include "pgweb.labels" . | indent 4 }}
{{- end -}}
