{{- $fullName := include "frontend.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.nodeHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName:  {{ .Release.Namespace }}-frontend
          servicePort: http