{{- $fullName := include "backend.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.nodeHost }}
    http:
      paths:
      - path: /swagger.json
        backend:
          serviceName:  {{ .Release.Namespace }}-backend
          servicePort: http
      - path: /api
        backend:
          serviceName:  {{ .Release.Namespace }}-backend
          servicePort: http
      - path: /socket.io
        backend:
          serviceName:  {{ .Release.Namespace }}-backend
          servicePort: http