"""Link EdgeAnnotation to Edge

Revision ID: 155fe996403c
Revises: ad520fd90bcd
Create Date: 2019-03-14 16:44:14.121169

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '155fe996403c'
down_revision = 'ad520fd90bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_information', sa.Column('edge_id', sa.Integer(), nullable=False))
    op.drop_constraint('edge_information_experiment_id_fkey', 'edge_information', type_='foreignkey')
    op.create_foreign_key(None, 'edge_information', 'edge', ['edge_id'], ['id'])
    op.drop_column('edge_information', 'from_node_name')
    op.drop_column('edge_information', 'to_node_name')
    op.drop_column('edge_information', 'experiment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_information', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('edge_information', sa.Column('to_node_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('edge_information', sa.Column('from_node_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'edge_information', type_='foreignkey')
    op.create_foreign_key('edge_information_experiment_id_fkey', 'edge_information', 'experiment', ['experiment_id'], ['id'])
    op.drop_column('edge_information', 'edge_id')
    # ### end Alembic commands ###
