"""docker preparation

Revision ID: 24dfdfe81378
Revises: 7c50c2f7f14e
Create Date: 2019-02-27 12:16:25.173542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24dfdfe81378'
down_revision = '7c50c2f7f14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm', sa.Column('docker_image', sa.String(), nullable=True))
    op.drop_column('algorithm', 'backend')
    op.add_column('job', sa.Column('container_id', sa.String(), nullable=True))
    op.drop_column('job', 'pid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('job', 'container_id')
    op.add_column('algorithm', sa.Column('backend', postgresql.ENUM('python', 'cpp', 'R', name='backendtype'), autoincrement=False, nullable=True))
    op.drop_column('algorithm', 'docker_image')
    # ### end Alembic commands ###
