"""Add edge weight, edge information, annotations

Revision ID: 419692981146
Revises: 7c50c2f7f14e
Create Date: 2019-02-20 15:09:15.426453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419692981146'
down_revision = '7c50c2f7f14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('annotation', sa.Enum('valid', 'invalid', name='edgeannotation'), nullable=False),
    sa.Column('from_node_name', sa.String(), nullable=True),
    sa.Column('to_node_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('edge', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edge', 'weight')
    op.drop_table('edge_information')
    # ### end Alembic commands ###
