"""Delete Sepset Names

Revision ID: 8e2bc5703148
Revises: ff86592aaca9
Create Date: 2019-02-19 15:44:23.998611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e2bc5703148'
down_revision = 'ff86592aaca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sepset', 'node_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sepset', sa.Column('node_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
