"""add docker params to algorithm

Revision ID: a56f13808882
Revises: 6afc1d19f183
Create Date: 2019-03-20 14:08:39.631522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56f13808882'
down_revision = '6afc1d19f183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm', sa.Column('docker_parameters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algorithm', 'docker_parameters')
    # ### end Alembic commands ###
