"""Added job error codes

Revision ID: 10a6275ef963
Revises: b56cebdb964a
Create Date: 2020-01-30 11:55:24.795742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10a6275ef963'
down_revision = 'b56cebdb964a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    joberrorcode = postgresql.ENUM('UNSCHEDULABLE', 'IMAGE_NOT_FOUND', 'UNKNOWN', name='joberrorcode')
    joberrorcode.create(op.get_bind())
    op.add_column('job', sa.Column('error_code',
                  sa.Enum('UNSCHEDULABLE', 'IMAGE_NOT_FOUND', 'UNKNOWN', name='joberrorcode'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'error_code')
    joberrorcode = postgresql.ENUM('UNSCHEDULABLE', 'IMAGE_NOT_FOUND', 'UNKNOWN', name='joberrorcode')
    joberrorcode.drop(op.get_bind())
    # ### end Alembic commands ###
