"""Change Algorithm Schema

Revision ID: 556615390357
Revises: 575e6124462f
Create Date: 2020-01-28 15:15:23.815869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556615390357'
down_revision = '575e6124462f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm', sa.Column('function', sa.String(), nullable=True))
    op.add_column('algorithm', sa.Column('package', sa.String(), nullable=True))
    op.drop_constraint('algorithm_name_key', 'algorithm', type_='unique')
    op.drop_column('algorithm', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('algorithm_name_key', 'algorithm', ['name'])
    op.drop_column('algorithm', 'package')
    op.drop_column('algorithm', 'function')
    # ### end Alembic commands ###
