"""Change edge information to include annotation information

Revision ID: 687912862702
Revises: a56f13808882
Create Date: 2019-03-26 12:02:32.127622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687912862702'
down_revision = 'a56f13808882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_information', sa.Column('from_node_id', sa.Integer(), nullable=False))
    op.add_column('edge_information', sa.Column('result_id', sa.Integer(), nullable=False))
    op.add_column('edge_information', sa.Column('to_node_id', sa.Integer(), nullable=False))
    op.drop_constraint('edge_information_edge_id_fkey', 'edge_information', type_='foreignkey')
    op.create_foreign_key(None, 'edge_information', 'node', ['from_node_id'], ['id'])
    op.create_foreign_key(None, 'edge_information', 'node', ['to_node_id'], ['id'])
    op.create_foreign_key(None, 'edge_information', 'result', ['result_id'], ['id'])
    op.drop_column('edge_information', 'edge_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_information', sa.Column('edge_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'edge_information', type_='foreignkey')
    op.drop_constraint(None, 'edge_information', type_='foreignkey')
    op.drop_constraint(None, 'edge_information', type_='foreignkey')
    op.create_foreign_key('edge_information_edge_id_fkey', 'edge_information', 'edge', ['edge_id'], ['id'])
    op.drop_column('edge_information', 'to_node_id')
    op.drop_column('edge_information', 'result_id')
    op.drop_column('edge_information', 'from_node_id')
    # ### end Alembic commands ###
