"""Add enforce_cpus

Revision ID: 6c819ffe83d6
Revises: 10a6275ef963
Create Date: 2020-02-18 14:47:08.090335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c819ffe83d6'
down_revision = '10a6275ef963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('enforce_cpus', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'enforce_cpus')
    # ### end Alembic commands ###
