"""Add node hostname

Revision ID: a0d6ed9fe467
Revises: dc1f7c0e8c6d
Create Date: 2019-12-11 22:25:30.556094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d6ed9fe467'
down_revision = 'dc1f7c0e8c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('node_hostname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'node_hostname')
    # ### end Alembic commands ###
