"""Add parallel selector to job

Revision ID: a79cc8fc4711
Revises: 575e6124462f
Create Date: 2020-01-28 12:25:19.018710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79cc8fc4711'
down_revision = '575e6124462f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('parallel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'parallel')
    # ### end Alembic commands ###
