"""Add is_ground_truth attribute and make result_id nullable

Revision ID: b047d3fb4b13
Revises: bde7db78a4fb
Create Date: 2019-10-29 13:00:43.997067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b047d3fb4b13'
down_revision = 'bde7db78a4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge', sa.Column('is_ground_truth', sa.Boolean(), nullable=True))
    op.alter_column('edge', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edge', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('edge', 'is_ground_truth')
    # ### end Alembic commands ###
