"""GPU count and needs GPU properties

Revision ID: b56cebdb964a
Revises: 7eacbdc4af1d
Create Date: 2020-01-29 16:57:30.615600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56cebdb964a'
down_revision = '7eacbdc4af1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm', sa.Column('needs_gpu', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('gpus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'gpus')
    op.drop_column('algorithm', 'needs_gpu')
    # ### end Alembic commands ###
