apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName:  {{ include "backend.fullname" . }}
          servicePort: 5000
      - path: /socket.io
        backend:
          serviceName:  {{ include "backend.fullname" . }}
          servicePort: 5000